#94: Extract logic for TgzArchive metata
artipie/helm-adapter pull request #101
Opened 2021-02-23 14:18 UTC by andreoss

- Extract method
- Refactor dependent classes

2021-02-25 12:01 UTC, genryxy requested changes
@andreoss thanks, see comments

2021-02-25 17:30 UTC, genryxy commented on src/main/java/com/artipie/helm/metadata/IndexYamlMapping.java
>              }
@andreoss also, now synchronized section includes more logic for processing. Previously this section includes only check does mapping contain specific key. Is it possible to reduce the amount of logic in synchronized block?

2021-02-27 03:54 UTC, andreoss commented on src/main/java/com/artipie/helm/metadata/IndexYaml.java
> +                    tgz.chartYaml().version()
@genryxy The existence check is in order to not update metadata twice.

2021-02-27 03:58 UTC, andreoss commented on src/test/java/com/artipie/helm/TgzArchiveTest.java
> +            )
@genryxy Done

2021-02-27 04:01 UTC, andreoss commented on src/main/java/com/artipie/helm/TgzArchive.java
> +     */
@genryxy

2021-02-27 04:01 UTC, andreoss commented on src/main/java/com/artipie/helm/TgzArchive.java
> +        meta.put("digest", this.digest());
@genryxy Removed the method

2021-02-27 04:09 UTC, andreoss commented on src/main/java/com/artipie/helm/metadata/IndexYamlMapping.java
>              }
@genryxy I left a todo to fix this.

2021-02-27 04:22 UTC, andreoss commented on src/test/java/com/artipie/helm/TgzArchiveTest.java
> +            ).metadata(Optional.empty()),
@genryxy Done

2021-02-27 18:22 UTC, genryxy commented on src/test/java/com/artipie/helm/TgzArchiveTest.java
> +    void hasCorrectMetadata() {
@andreoss why do we need suppress warning here?

2021-02-27 18:24 UTC, genryxy commented on src/main/java/com/artipie/helm/metadata/IndexYaml.java
> +                    tgz.chartYaml().version()
@andreoss ok, got it

2021-02-27 22:41 UTC, andreoss commented on src/test/java/com/artipie/helm/TgzArchiveTest.java
> +    void hasCorrectMetadata() {
@genryxy There's an issue with type inference on JDK 8. It's not needed on JDK 11

2021-02-28 04:06 UTC, genryxy submitted a review, later dismissed
@andreoss thanks, looks good to me
@g4s8 please check/merge

2021-03-01 07:46 UTC, g4s8 requested changes
@andreoss please check my comment

2021-03-01 07:46 UTC, g4s8 commented on pom.xml
> +          -->
@andreoss why it's related to #94 ticket? It doesn't seem to be a part of the task, so it should be reported as a new ticket, not as a todo for #94

2021-03-01 14:16 UTC, andreoss commented on pom.xml
> +          -->
@g4s8 It constantly comes up on review. Is there a difference between the issues reported via pdd or manually besides the issues will be linked?

2021-03-04 08:13 UTC, g4s8 commented on pom.xml
> +          -->
@andreoss yes, it allows to control the scope better by filtering different kind of tasks and building the tree of subtasks as dependencies, so we'll have better granularity of scope in that case.

2021-03-12 16:44 UTC, genryxy commented
@andreoss could you please remove todo and it will be fine

2021-03-12 18:16 UTC, genryxy approved these changes
@andreoss thanks, approve
@g4s8 could you please check/merge

2021-03-16 08:25 UTC, g4s8 approved these changes
@andreoss thanks

2021-03-16 08:25 UTC, merged

2021-03-16 09:28 UTC, 0crat commented
Job `gh:artipie/helm-adapter#101` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/9c3d8895-a7d3-4040-b680-6256188b8514, version: 0.55.1, hash: ${buildNumber} -->