Add skeleton for batch update, add parameter to disable index update
artipie/helm-adapter pull request #111
Opened 2021-04-20 14:29 UTC by genryxy

Part of #109 
Added skeleton for batch update. 
Added parameter to disable index update for single upload in `PushChartSlice and tested it`

2021-04-20 14:52 UTC, olenagerasimova requested changes
@genryxy thanks, please, check my comments

2021-04-20 14:52 UTC, olenagerasimova commented on src/main/java/com/artipie/helm/Helm.java
> +    CompletionStage<Void> batchUpdate(Key prefix);
@genryxy is this sdk API discussed with CMC team? Lately they want to work with input/output steams, not with file storage.

2021-04-20 14:52 UTC, olenagerasimova commented on src/main/java/com/artipie/helm/http/PushChartSlice.java
> +                        if (!upd.isPresent() || upd.get().equals("true")) {
@genryxy I'd suggest to simplify by using `isEmpty()` method

2021-04-20 14:56 UTC, genryxy commented on src/main/java/com/artipie/helm/http/PushChartSlice.java
> +                        if (!upd.isPresent() || upd.get().equals("true")) {
@olenagerasimova `isEmpty()` appeared later, not since `Java 8` therefore `isPresent()` was used

2021-04-20 14:59 UTC, genryxy commented on src/main/java/com/artipie/helm/Helm.java
> +    CompletionStage<Void> batchUpdate(Key prefix);
@olenagerasimova no, it was not discussed. I'll write them to to establish format

2021-04-21 09:35 UTC, olenagerasimova commented on src/main/java/com/artipie/helm/http/PushChartSlice.java
> +                        if (!upd.isPresent() || upd.get().equals("true")) {
@genryxy oh, sorry, my bad

2021-04-21 09:36 UTC, olenagerasimova approved these changes
@genryxy thanks for the responses, approving, please, do not forget to discuss sdk api with our colleagues.

2021-04-21 09:36 UTC, merged