Add index reader for extracting versions
artipie/helm-adapter pull request #112
Opened 2021-04-26 12:13 UTC by genryxy

Part of #109 
Added `IndexReader` for obtaining versions for included packages. For now index is written to temporary file storage. 
Later probably it will be replaced with converter from `Publisher<ByteBuffer>` to another  `Publisher<ByteBuffer>` which is splitted by breaks (based on implementation of `org.reactivestreams.Processor`).

2021-04-28 13:44 UTC, g4s8 requested changes
@genryxy thanks. Please see my comments. Also, I'd add a todo for replacing parser with reactive version to avoid copying index file to temp storage.

2021-04-28 13:44 UTC, g4s8 commented on src/main/java/com/artipie/helm/metadata/IndexReader.java
> +public interface IndexReader {
@genryxy I'd call this class just `Index`

2021-04-28 13:44 UTC, g4s8 commented on src/main/java/com/artipie/helm/metadata/IndexReader.java
> +                final Path file = Files.createTempFile(tmp, prefix, ".yaml");
@genryxy please move all IO operations into async task - when you return `CompletionStage`, it's assumed that the operation is asynchronous, and it doesn't perform some blocking operations here:
```java
CompletableFuture.runAsync(() -> {...})
```

2021-04-28 13:44 UTC, g4s8 commented on src/main/java/com/artipie/helm/metadata/IndexReader.java
> +            } catch (final IOException exc) {
@genryxy when returning `CompletionStage` you can emit error into result future, e.g. `future.completeExceptionaly(err)` or similar

2021-04-28 13:44 UTC, g4s8 commented on src/main/java/com/artipie/helm/metadata/IndexReader.java
> +                            name = trimmed.replace(colon, empty);
@genryxy you can just use `":"` and `""` here -- these strings will be interned

2021-04-28 13:44 UTC, g4s8 commented on src/main/java/com/artipie/helm/metadata/IndexReader.java
> +         * Parses index file and extracts versions for packages.
@genryxy these method looks too complex -- I'd add more documentation on it

2021-04-28 13:44 UTC, g4s8 commented on src/test/java/com/artipie/helm/metadata/IndexReaderWithBreaksTest.java
> +        storage.save(
@genryxy you can use `BlockingStorage` in tests to prepare the data, it may look a bit clearer: `bst.save(INDEX_YAML, new TestResource(index).asBytes())`

2021-04-28 14:13 UTC, genryxy commented
@g4s8 thanks, corrected

2021-04-29 07:37 UTC, g4s8 approved these changes
@genryxy thanks

2021-04-29 07:38 UTC, merged

2021-04-29 07:38 UTC, 0pdd commented
@genryxy the puzzle [#113](https://github.com/artipie/helm-adapter/issues/113) is still not solved.

2021-07-16 12:19 UTC, 0pdd commented
@genryxy the puzzle [#187](https://github.com/artipie/helm-adapter/issues/187) is still not solved; solved: [#113](https://github.com/artipie/helm-adapter/issues/113).

2021-07-16 15:58 UTC, 0pdd commented
@genryxy 2 puzzles [#187](https://github.com/artipie/helm-adapter/issues/187), [#188](https://github.com/artipie/helm-adapter/issues/188) are still not solved; solved: [#113](https://github.com/artipie/helm-adapter/issues/113).

2021-07-19 13:16 UTC, 0pdd commented
@genryxy the puzzle [#188](https://github.com/artipie/helm-adapter/issues/188) is still not solved; solved: [#113](https://github.com/artipie/helm-adapter/issues/113), [#187](https://github.com/artipie/helm-adapter/issues/187).