Add benchmark for remove operation
artipie/helm-adapter pull request #135
Opened 2021-05-17 14:30 UTC by genryxy

Part of #121 
Added benchmark for remove operation. 
For benchmarks a separate Maven project in subdirectory of this project was created. I'm not sure about including `ppom` in parent for `pom.xml` in benchmarks but without it `qulice` is not included.
Readme will be updated in next PR.

2021-05-20 12:48 UTC, genryxy commented
@g4s8 could you please take a look

2021-05-20 14:26 UTC, g4s8 requested changes
@genryxy please see my comment

2021-05-20 15:55 UTC, genryxy commented
@g4s8 thanks, corrected

2021-05-21 06:25 UTC, g4s8 requested changes
@genryxy please see my comments

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +    private final Map<Key, Boolean> items;
I'd rename this field to make it more descriptive, e.g. `existence` or similar

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +                synchronized (this.items) {
Maybe we can use some thread safe non-blocking collection instead of synchronization block? This block could affect the performance during benchmarks, since JMH runs many benchmarks in parallel (we need fast read and may have slow write)

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +        synchronized (this.storage) {
I'm not sure the synchronization here is needed

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +        synchronized (this.storage) {
Here synchronization is redundant, since `save` is asynchronous operation, and it returns immediately from `synchronized` block.

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +                        synchronized (this.items) {
Here we can use thread-safe non-blocking collection with fast read access instead of `synchronized` block

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +                synchronized (this.items) {
Same here

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +        throw new NotImplementedException("not implemented");
Why `size` is not used? We can just delegate it to underlying `storage`

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +        synchronized (this.storage) {
Same here

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +                synchronized (this.items) {
Same here

2021-05-21 06:25 UTC, g4s8 commented on benchmarks/src/main/java/com/artipie/helm/BenchStorage.java
> +                synchronized (this.items) {
Same here

2021-05-21 09:17 UTC, genryxy commented
@g4s8 thanks, used `ConcurrentMap`. All files are saved to storage before running benchmark. After each invocation flags for existed values are reset to true

2021-05-24 07:19 UTC, g4s8 commented
@olenagerasimova can you please check this benchmark too?

2021-05-24 07:51 UTC, olenagerasimova approved these changes
@genryxy looks good to me, the only possible improvement I see is to wrap `BenchStorage` into `BlockingStorage` to avoid constant `.join()` calls

2021-05-24 08:17 UTC, genryxy commented
@olenagerasimova in this case it would be impossible to call `reset()` method which is not included to storage interface

2021-05-24 08:20 UTC, olenagerasimova commented
@genryxy ok, I see

2021-05-24 08:48 UTC, g4s8 approved these changes
@genryxy thanks

2021-05-24 08:48 UTC, merged