Add prefix for `add` operation
artipie/helm-adapter pull request #141
Opened 2021-05-20 14:35 UTC by genryxy

Closes #139 
Added prefix for `add` operation. Added negative tests for keys with incorrect prefix

2021-05-24 06:03 UTC, genryxy commented
@g4s8 could you please take a look

2021-05-28 08:34 UTC, genryxy commented
@g4s8 could you please check this PR

2021-05-28 08:50 UTC, g4s8 requested changes
@genryxy please check my comments

2021-05-28 08:50 UTC, g4s8 commented on src/main/java/com/artipie/helm/Helm.java
> +     * @param prefix Path to index file
The name of the variable seems to be wrong, I'd call it `index` or similar

2021-05-28 08:50 UTC, g4s8 commented on src/main/java/com/artipie/helm/Helm.java
> +    CompletionStage<Void> add(Collection<Key> charts, Key prefix);
I'd recommend introducing a `CHANGELOG` file in repo root to track all important changes here to properly handle new versions names. We can maintain it as follows: starts block with version placeholder, e.g. `__NEXT__`, then describe changes with some prefixes:
 - fix - for bug fixes
 - new - for new functionality
 - break - for breaking changes

e.g.:
```
__NEXT__
break: #141 - Helm SDK API changed, added Key parameter
```
This way we'll handle updates correctly by reviewing last changes and updating the `__NEXT__` placeholder with major bump if needed.

2021-05-28 09:02 UTC, genryxy commented on src/main/java/com/artipie/helm/Helm.java
> +    CompletionStage<Void> add(Collection<Key> charts, Key prefix);
@g4s8 okay, got it. I'll create this file. By the way, Helm SDK API has not been yet released

2021-05-28 09:02 UTC, genryxy commented
@g4s8 thanks, renamed

2021-05-28 14:46 UTC, merged