Remove temporary directories
artipie/helm-adapter pull request #148
Opened 2021-05-28 14:55 UTC by genryxy

Closes #142 
Remove temporary directories which are left after `remove` and `add` operations. Added tests for it.

2021-06-02 07:22 UTC, g4s8 requested changes
@genryxy sorry ,forget to submit the review

2021-06-02 07:44 UTC, genryxy commented on src/main/java/com/artipie/helm/AddWriter.java
> +                            FileUtils.deleteQuietly(out.getParent().toFile());
@g4s8 in this case it won't work because if this operation normally finished we need to move file from temporary storage to the real storage. After moving temporary files will be deleted. But if `add` operation throws an exception, we won't enter to the section where moving from temporary storage to the real storage happens, therefore it is necessary to delete temp directory in catch section

2021-06-02 09:27 UTC, g4s8 commented on src/main/java/com/artipie/helm/AddWriter.java
> +                            FileUtils.deleteQuietly(out.getParent().toFile());
In this case it can be removed at upper lavel where temp dir is removed in positive case. It couldbe done using `handle()` method of `CompletionStage`

2021-06-03 06:30 UTC, genryxy commented
@g4s8 thanks, corrected

2021-06-03 13:54 UTC, g4s8 approved these changes
@genryxy thanks

2021-06-03 13:54 UTC, merged