Reindex packages in repo
artipie/helm-adapter pull request #163
Opened 2021-06-28 10:06 UTC by genryxy

Closes #115 
Added reindexing packages in repo by prefix. 
Added tests for this

2021-06-28 11:09 UTC, olenagerasimova requested changes
@genryxy thanks, please, check my comments

2021-06-28 11:09 UTC, olenagerasimova commented on src/main/java/com/artipie/helm/Helm.java
> +                                ).handle(
@genryxy seems like is would be more correct to handle all the possible errors and remove temp dir on the most external futures chain.

2021-06-28 12:26 UTC, genryxy commented on src/main/java/com/artipie/helm/Helm.java
> +                            final SortedSet<Key> tgzs = new TreeSet<>(Key.CMP_STRING);
@olenagerasimova As I understand creating temporary directory is no an immediate operation, therefore it should be placed in an asynchronous block (according to [this comment](https://github.com/artipie/helm-adapter/pull/112#discussion_r622187235)). I think that update won't start if an error will be occurred during creating a temporary directory because it would go to `catch` block after throwing such exception

2021-06-28 12:52 UTC, genryxy commented on src/main/java/com/artipie/helm/Helm.java
> +                                ).handle(
@olenagerasimova probably to move block with creation temp dir to the first section of section? So, if an exception is occurred during creation of temporary directory, it won't start reading all keys from storage and filtering them.

2021-07-01 12:18 UTC, genryxy commented
@olenagerasimova could you please take a look

2021-07-01 12:24 UTC, olenagerasimova requested changes

2021-07-01 12:25 UTC, olenagerasimova commented
@genryxy hm, please, check my comments, I do not see any answers or changes...

2021-07-01 14:09 UTC, olenagerasimova requested changes
@genryxy thanks, please check one suggestion to simplify code

2021-07-01 14:09 UTC, olenagerasimova commented on src/main/java/com/artipie/helm/Helm.java
> +            CompletableFuture.supplyAsync(
@genryxy sorry, I was wrong to suggest `supplyAsync`, `runAsync` is better here, it returns `Void`, there should not be any need for `thenCompose(Function.identity())`

2021-07-02 05:23 UTC, olenagerasimova approved these changes
@genryxy thanks, approving

2021-07-02 05:23 UTC, merged