Use tokenizer instead of copying index in `Index.WithBreaks`
artipie/helm-adapter pull request #176
Opened 2021-07-08 12:35 UTC by genryxy

Part of #113 
Use reactive tokenizer instead of copying index file in temporary file. Changed a bit test because now it is not necessary to check existence of temporary directories.

2021-07-09 13:35 UTC, genryxy commented
@g4s8 @olenagerasimova could please someone take a look

2021-07-12 06:24 UTC, g4s8 requested changes
@genryxy please check my comment

2021-07-12 06:24 UTC, g4s8 commented on src/main/java/com/artipie/helm/metadata/Index.java
> +            final Map<String, Set<String>> vrns = new ConcurrentHashMap<>();
This section looks like a global memory for reactive processing, it's actually hard to read and understand now, because the execution flow is lazy and asynchronous: we don't know when and in what thread the reactive lambda body will be executed, or how many threads will execute it simultaneously.

I'd suggest using some kind of reducer here to share context and reduce the input data into output `Map`, something like: `Flowable.fromPublisher(target).reduce(new Map<>(), (map, line) -> {})`

2021-07-12 07:13 UTC, genryxy commented on src/main/java/com/artipie/helm/metadata/Index.java
> +            final Map<String, Set<String>> vrns = new ConcurrentHashMap<>();
@g4s8 do I understand correct that in this case whole index file will be read to memory and will be stored in map? In addition, some lines may be repeated.

2021-07-12 07:22 UTC, g4s8 commented on src/main/java/com/artipie/helm/metadata/Index.java
> +            final Map<String, Set<String>> vrns = new ConcurrentHashMap<>();
@genryxy no, the reducer process each item one by one. But it allows you to accumulate some result in accumulator object (e.g. `Map`)

2021-07-12 12:28 UTC, genryxy commented
@g4s8 thanks, I tried to simplify using `scan` as it was suggested. Please take a look

2021-07-15 20:04 UTC, genryxy commented
@g4s8 could you please take a look

2021-07-16 11:30 UTC, g4s8 requested changes
@genryxy please check my comment

2021-07-16 11:30 UTC, g4s8 commented on src/main/java/com/artipie/helm/metadata/Index.java
> +            final String empty = "";
I think you can introduce additional object to keep the flow context and safely use it inside scan operation, this way you have guarantee that order of operations and thread-safety, e.g.:
```java
class ScanContext {
  int indent;
  vrns Map<>; // what is verns?
  in boolean;
  String last; // last item
}
// ...
.scan(new ScanContext(), (ctx, last) -> {
  // work with context
  ctx.last = last;
  return ctx;
})
```

2021-07-16 12:16 UTC, genryxy commented
@g4s8 thanks, used context class

2021-07-16 12:18 UTC, g4s8 approved these changes
@genryxy thanks, looks good now

2021-07-16 12:19 UTC, merged