Use tokenizer instead of copying index for `add`
artipie/helm-adapter pull request #177
Opened 2021-07-08 19:05 UTC by genryxy

Part of #113
Use reactive tokenizer for `add` instead of copying index file in temporary file. Now it reads line by line from source file and write a new index to a temporary file which at the end replaces source index file

2021-07-12 07:51 UTC, g4s8 requested changes
@genryxy please check my comment

2021-07-12 07:51 UTC, g4s8 commented on src/main/java/com/artipie/helm/AddWriter.java
> +                        linewrtr.set(new LineWriter(writer.get()));
Here is the same problem as in another PR: global context variables are hard to read and understand (and they may contain concurrency bugs), please use some reducer to provide operation context

2021-07-13 08:27 UTC, genryxy commented
@g4s8 thanks, I tried to simplify using `scan` as it was suggested. Also I noticed that class `LineWriter` is extra and could be simply included in class `YamlWriter`

2021-07-15 20:04 UTC, genryxy commented
@g4s8 could you please take a look

2021-07-16 14:42 UTC, genryxy commented
@g4s8 please check

2021-07-16 15:57 UTC, g4s8 approved these changes
@genryxy thanks

2021-07-16 15:58 UTC, merged