deps: bump `ppom` and other deps, extract benchmarks as a module
artipie/helm-adapter pull request #249
Opened 2021-11-22 14:06 UTC by genryxy

Moved `org.cactoos` to test dependency.
Bumped `http` to `v1.0.1`., `asto` to `v1.9.0`, `vertx-server` to `0.5`. Also I had to add `org.junit.vintage` dependency because it did not work without it

2021-11-23 13:58 UTC, olenagerasimova requested changes
@genryxy thanks, check my suggestion please

2021-11-23 13:58 UTC, olenagerasimova commented on benchmarks/src/main/java/com/artipie/helm/HelmAstoAddBench.java
> +                        }
hm, please, try `UncheckedIOScalar` from asto, it does exactly what is written here...

2021-11-23 13:58 UTC, olenagerasimova commented on benchmarks/src/main/java/com/artipie/helm/HelmAstoReindexBench.java
> +                    }
same here

2021-11-23 13:58 UTC, olenagerasimova commented on benchmarks/src/main/java/com/artipie/helm/HelmAstoRemoveBench.java
> +                    }
and here

2021-11-23 15:05 UTC, genryxy commented
@olenagerasimova thanks, corrected

2021-12-01 14:00 UTC, genryxy commented
@olenagerasimova could you please check

2021-12-01 14:14 UTC, olenagerasimova approved these changes
@genryxy thanks

2021-12-01 14:16 UTC, merged

2021-12-01 14:19 UTC, olenagerasimova commented
@genryxy thanks, sorry for the delay