Helm compatibility test
artipie/helm-adapter pull request #56
Opened 2020-07-06 10:06 UTC by Sammers21

Created a test which ensures that the created repository could be recognized by helm.

Under the hood, the `helm repo add` and `helm repo update` commands are fetching the index.yaml file and storing them in the $XDG_CACHE_HOME/helm/repository/cache/ directory. 

Related to #8

2020-07-06 10:06 UTC, Sammers21 commented
@olegmoz, can you review?

2020-07-06 10:24 UTC, 0crat commented
This pull request [#56](https://github.com/artipie/helm-adapter/issues/56) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/745fc337-bc55-458b-b93e-0199348cb1b4); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

<!-- https://www.0crat.com/footprint/CT2E6TK9B/5c7cabad-dc15-4453-a0a9-32a97c3cce4b, version: 0.53.15, hash: ${buildNumber} -->

2020-07-06 11:08 UTC, olegmoz commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +        final VertxSliceServer server = new VertxSliceServer(vertx, new HelmSlice(fls, turl), port);
@Sammers21 I'd suggest to move server & client staring code to a `@SetUp` method, it would make test code more focused and reduce code duplication in this test class

2020-07-06 11:13 UTC, olegmoz commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            exec(helm, "helm", "repo", "update");
@Sammers21 that is good practice to have single `MatcherAssert.assertThat` statement in test and do such assertion about the thing that is tested. In this test you need to make an assertion only for `help repo update` command and not do such assertion for `helm init` and `help repo add` commands

2020-07-06 11:15 UTC, olegmoz commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            );
@Sammers21 this does not look like proper `MatcherAssert.assertThat` usage, see my other comment. It would be better to replace with common exception

2020-07-06 11:27 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +        final VertxSliceServer server = new VertxSliceServer(vertx, new HelmSlice(fls, turl), port);
What if I would need to change the served slice for a particular test?

2020-07-06 11:29 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            exec(helm, "helm", "repo", "update");
@olegmoz, having more assets makes more sense to me

2020-07-06 11:34 UTC, olegmoz commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +        final VertxSliceServer server = new VertxSliceServer(vertx, new HelmSlice(fls, turl), port);
@Sammers21 then you will have a problem, this is not really the case for tests here. First test will run just great with slice from second test. Anyway that's a suggestion

2020-07-06 11:37 UTC, olegmoz commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            exec(helm, "helm", "repo", "update");
@Sammers21 it should not! Assertions (and yes, there could be many) should be done only about things you are testing. And you are making assertions about success of preparation steps (say initializing helm). That is bad practice and makes tests less understandable.

2020-07-06 12:12 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            exec(helm, "helm", "repo", "update");
Why do you think it's a bad practice for an expensive integration test?

2020-07-06 12:37 UTC, olegmoz commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            exec(helm, "helm", "repo", "update");
@Sammers21 bad practice is to throw `AssertionError` on something unrelated to test subject. When `helm init` fails for some reason it is not something you are testing and you should not throw `AssertionError` in this case

2020-07-06 13:42 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            exec(helm, "helm", "repo", "update");
I guess, but from the progmatic point of view it does not matter how the test fails. The only important thing is _where_

2020-07-06 18:55 UTC, olegmoz commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            exec(helm, "helm", "repo", "update");
@Sammers21 it's the same as saying that only thing important about code is if it is working or not. Making assertions only in test method only where they are needed emphases what is being tested. It makes tests more readable. Also test runners distinguish `AssertionError` from other exceptions, that makes test run results more clear. So I still insist on making proper use of assertions in this test

2020-07-06 19:21 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            exec(helm, "helm", "repo", "update");
@olegmoz, in this case code would look uglier, more complex to understand and hard to read , while error message will be the same.

2020-07-06 19:24 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            exec(helm, "helm", "repo", "update");
> not do such assertion for helm init and help repo add commands

Helm repo add should be asserted 100%:

> Under the hood, the helm repo add and helm repo update commands are fetching the index.yaml

2020-07-07 08:31 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            );
@Sammers21 it's not actually a test code but a preparation for test, it can be moved to `@BeforeEach` setup function.

2020-07-07 08:32 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            }
@Sammers21 why do we need to verify that? Let's just assume that other logic expect code under test works correctly.

2020-07-07 08:33 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            MatcherAssert.assertThat(
@Sammers21 please use assertion messages when testing multiple statements in one test

2020-07-07 08:33 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +        }
@Sammers21 it can be moved to `@AfterEach` func

2020-07-07 08:41 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            );
@g4s8, It would not be reused anyway.

2020-07-07 08:41 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            }
@g4s8, if it fails we should stop

2020-07-07 08:47 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            );
@Sammers21 it's not about reuse, it's about test reports, lifecycle and readability. When `BeforeEach` function fails, failsafe reports that test can't be run. But if it fails inside method body, it reports that `helmRepoAddWorks` fails. Also, it would be clearer for reader to see only testing code inside test method, not preparation steps.

2020-07-07 08:48 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            }
@Sammers21 but it's not related to `helmRepoAddWorks` test, isn't it? Slice will fail in any case if slice-server won't start.

2020-07-07 09:19 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            );
> Also, it would be clearer for reader to see only testing code inside the test method, not preparation steps.

@g4s8, Disagree. Fist. The case is not the only one in the class. Second: preparation steps also a part of the case and it would look better for anyone when it is in a single place.

2020-07-07 09:21 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            );
To put it simply, we don't need `BeforeEach` and `AfterEach` because the preparation step might be different and it more readable in one place.

2020-07-07 09:22 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +            }
Related, helm repo should contain a package in order to be indexed and validated.

2020-07-07 17:31 UTC, Sammers21 commented
@g4s8, can we merge?

2020-07-08 07:33 UTC, Sammers21 commented
@g4s8, ping

2020-07-08 10:03 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@Sammers21 I don't think these changes deserves separate ticket. It's just a small refactoring to move few lines of code to another method.

2020-07-08 10:44 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@g4s8, it is not a small refactoring. 3 classes will be created in the worst case

2020-07-08 13:16 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@Sammers21 can we just move these lines to `@BeforeEach` method? Why do we need to create new classes for this test?

2020-07-08 13:31 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@g4s8, there 2 test cases in the class. The preparation steps might be different, that is why we need a class for the container, a class for random port functionality, and a class for a new test where we can put the mentioned annotations.

2020-07-08 13:32 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@g4s8, i already did it locally. Just merge the PR and will send another PR.

2020-07-08 13:59 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@Sammers21 then why do we need this PR if you are going to change test implementation right after merging? It will be just a waste of time, isn't it?

2020-07-08 14:14 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@g4s8, because the change is not trivial and you will need a few more days for a review

2020-07-08 14:38 UTC, g4s8 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@Sammers21 I don't see any reasons in merging pull request just to change it right after that.

2020-07-08 14:40 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@g4s8, what is wrong with it? It is microtasking

2020-07-08 14:44 UTC, Sammers21 commented on src/test/java/com/artipie/helm/SubmitChartITCase.java
> +     *  methods.
@g4s8, merging code in small portions better then merging in big portions. It should be okay since we have a puzzle.

2020-07-09 07:24 UTC, Sammers21 commented
> 2. Test contains unrelated checks for `GET /localhost`.

Where?

2020-07-09 07:46 UTC, g4s8 commented
> > 1. Test contains unrelated checks for `GET /localhost`.
> 
> @g4s8, Where did you find it?

@Sammers21 these lines: https://github.com/artipie/helm-adapter/pull/56/files#diff-fb432cd58c6ceaa3f034c8178275f7cfR171-R181

2020-07-09 07:49 UTC, Sammers21 commented
> > > 1. Test contains unrelated checks for `GET /localhost`.
> > 
> > 
> > @g4s8, Where did you find it?
> 
> @Sammers21 these lines: https://github.com/artipie/helm-adapter/pull/56/files#diff-fb432cd58c6ceaa3f034c8178275f7cfR171-R181

It is a post request. The test would not pass without it. A tomcat package is loaded in order to generate a valid index.yaml

2020-07-09 08:30 UTC, g4s8 commented
@Sammers21 if it's a part of integration test, it should be checked with assertion, not using exceptions

2020-07-09 08:36 UTC, Sammers21 commented
@g4s8, discuss it with @olegmoz: https://github.com/artipie/helm-adapter/pull/56#discussion_r450152153. You have the opposite opinions.

> @Sammers21 if it's a part of integration test, it should be checked with assertion, not using exceptions

2020-07-09 15:12 UTC, g4s8 commented
> @g4s8, discuss it with @olegmoz: [#56 (comment)](https://github.com/artipie/helm-adapter/pull/56#discussion_r450152153). You have the opposite opinions.
> 
> > @Sammers21 if it's a part of integration test, it should be checked with assertion, not using exceptions

@Sammers21 I just say that it seems to be unrelated to test, if it's testing target it should be verified using assertions. If it's not a test code, it should be moved to preparation steps.

2020-07-13 09:00 UTC, 0crat commented
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

<!-- https://www.0crat.com/footprint/CT2E6TK9B/e9f0d447-e3dc-4c51-877b-017f4809db8b, version: 0.54.5, hash: ${buildNumber} -->

2020-07-13 09:04 UTC, g4s8 commented
@0crat out

2020-07-13 11:47 UTC, Sammers21 commented
@g4s8, this PR was closed because you were not able to discuss the problem in #56. In a condition when two reviewers have opposite opinions on a topic it is impossible to merge a Pull Request. I will continue my work when @g4s8 will stop ignoring and come to a consensus with #56.

2020-07-13 11:51 UTC, olegmoz commented
@Sammers21 I do not see any contradictions in my comments and ones by Kirill. In any case he is the architect and my opinion is secondary, no discussion is needed.

2020-07-13 11:58 UTC, g4s8 commented
@Sammers21 I also don't see any contradictions with comments by @olegmoz. @Sammers21 please shows where exactly is the contradiction.

2020-07-13 12:04 UTC, Sammers21 commented
@g4s8, @olegmoz: https://github.com/artipie/helm-adapter/pull/56#discussion_r450152153

2020-07-13 12:31 UTC, g4s8 commented
> @g4s8, @olegmoz: [#56 (comment)](https://github.com/artipie/helm-adapter/pull/56#discussion_r450152153)

@Sammers21 my question was not about assert vs exception, it was about correctness of this statement: do we really need to upload something using slice to verify that Helm can add a repo? Your tests called `helmRepoAddWorks` it means it verifies that `helm` tool can add a repo, so uploading some package via `HelmSlice` looks unrelated to this test. I think it would be more correct to prepare some charts resources and run Helm slice using it.

2020-07-14 09:21 UTC, Vatavuk commented
@g4s8 please remove this issue from the scope

2020-07-14 10:12 UTC, 0crat commented
Job [#56](https://github.com/artipie/helm-adapter/issues/56) is already in scope

<!-- https://www.0crat.com/footprint/CT2E6TK9B/23e05848-bf3d-44f2-a2d3-41e5c1d3ac90, version: 0.54.5, hash: ${buildNumber} -->

2020-07-22 07:34 UTC, g4s8 commented
@0crat out

2020-07-30 13:27 UTC, Vatavuk commented
@0crat refuse

2020-08-06 18:19 UTC, Sammers21 commented
@g4s8, review the pull request.

2020-08-18 13:06 UTC, Sammers21 commented
@g4s8, @olegmoz, review the PR, please.

2020-08-19 09:11 UTC, g4s8 requested changes
@Sammers21 please check my comments

2020-08-19 09:24 UTC, Sammers21 commented on src/test/java/com/artipie/helm/EnsureIndexIsGoodITCase.java
> +public class EnsureIndexIsGoodITCase {
@g4s8, which one would you suggest?

2020-08-19 09:25 UTC, Sammers21 commented on src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
> +    }
@g4s8, yes, if you want to suggest a better way, feel free to do it.

2020-08-19 13:38 UTC, Sammers21 commented
@g4s8, please review the PR one more time, please.

2020-08-20 08:27 UTC, Sammers21 commented
@olegmoz, can you review the Pull Request, please?

2020-08-20 09:19 UTC, olegmoz requested changes
@Sammers21 I think that @g4s8 had valid concerns in his review, provided answers to you questions. Please address them and it will be good to merge

2020-08-20 09:19 UTC, olegmoz commented on src/test/java/com/artipie/helm/EnsureIndexIsGoodITCase.java
> +public class EnsureIndexIsGoodITCase {
@Sammers21 test class name is usually about entity (class) being tested. In this class you are testing `HelmSlice` when it is working with real storage inside real server. So I think that `HelmSliceIT` will be a good name.

2020-08-20 09:19 UTC, olegmoz commented on src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
> +    }
@Sammers21 I guess you may use a little bit more lightweight approach without starting a `Vertx` instance and whole HTTP server:
```java
try (ServerSocket socket = new ServerSocket(0)) {
  return socket.getLocalPort();
}
```

2020-08-24 08:02 UTC, Sammers21 commented on src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
> +    }
@olegmoz, did it a lot of times before. Kirill did not like it.

2020-08-24 10:44 UTC, olegmoz commented
@Sammers21 maybe in those cases he wanted to you to take port from ‘Vertx.start()’ method when you did not have to create ‘Slice’ with port? Could you please provide a link to his comments?

2020-08-25 08:19 UTC, Sammers21 commented
@olegmoz, yes, take a look: https://github.com/artipie/gem-adapter/pull/28#discussion_r413577798

2020-08-25 08:38 UTC, olegmoz commented
@Sammers21 as I expected, there it was possible to know port after you run the server, not before that. That is totally different.

Btw, you can do it here as well. There is no reason to provide real port to `HelmSlice`. Here is what you can do in `before()`:
```java
this.server = new VertxSliceServer(
    this.vertx,
    new HelmSlice(fls, "artipie.com/whatever")
);
final int port = this.server.start();
this.turl = String.format("http://host.testcontainers.internal:%d/", port);
Testcontainers.exposeHostPorts(port);
```
Then there is not need in `rndPort` method altogether.

2020-08-25 09:29 UTC, Sammers21 commented
@olegmoz, I need port the server will be started on before creating a helm slice.

2020-08-25 09:32 UTC, olegmoz commented
@Sammers21 are you sure that you need to pass correct port to the Slice? Won't the test pass if invalid URLis provided as it done in my snippet?

2020-08-25 09:38 UTC, Sammers21 commented
@g4s8, I don't know. I want to pass a valid url.

2020-08-25 10:41 UTC, olegmoz commented
@Sammers21 if you want the URL to be correct then please make port selection simpler using `ServerSocket` or use Maven plugin as described by @g4s8 in https://github.com/artipie/gem-adapter/pull/28#discussion_r413577798
Current implementation of `rndPort` is over-complicated without good reason.

2020-08-25 11:54 UTC, Sammers21 commented
@olegmoz, with maven plugin you can't debug, while ServerSocket solution were rejected by Kirill

2020-08-25 12:37 UTC, olegmoz commented
@Sammers21 please re-read Kirill's comments, you are getting his concerns wrong. Anyhow his recommended solution was Maven plugin, which is reliable and unlikely to require debugging. Then again, my opinion is that `ServerSocker` solution is fine too and definitely better that what we have in the PR.

2020-08-25 14:34 UTC, Sammers21 commented
@olegmoz, how exactly it is "definitely better"?

2020-08-25 14:59 UTC, olegmoz commented
@Sammers21 it's less code

2020-08-25 15:03 UTC, Sammers21 commented
@olegmoz, it is less code but more reliable than the `ServerSocker` approach.

2020-08-25 15:14 UTC, olegmoz commented
@Sammers21 reliable? What do you mean?

2020-08-26 07:33 UTC, Sammers21 commented
@olegmoz, `ServerSocker` sometimes fail.

2020-08-26 07:53 UTC, olegmoz commented
@Sammers21 please explain how `ServerSocker` is less reliable then starting Vertx HTTP server

2020-08-26 07:55 UTC, Sammers21 commented
@olegmoz, `ServerSocker ` sometimes fail, Vert.x server does not

2020-08-26 08:40 UTC, olegmoz commented
> @olegmoz, `ServerSocker ` sometimes fail, Vert.x server does not

@Sammers21 that's just a statement, not an explanation

2020-08-26 08:49 UTC, Sammers21 commented
@olegmoz, review the PR once again, please

2020-08-26 09:02 UTC, olegmoz requested changes
@Sammers21 thanks, the other issue about test class name is still unresolved, see https://github.com/artipie/helm-adapter/pull/56#discussion_r473799853

2020-08-26 09:03 UTC, Sammers21 commented
@olegmoz, review the PR once again, please

2020-08-26 09:14 UTC, olegmoz requested changes
@Sammers21 you renamed wrong file, the concern was about `EnsureIndexIsGoodITCase` class name

2020-08-26 09:25 UTC, Sammers21 commented
@olegmoz, review the PR once again, please

2020-08-26 09:26 UTC, olegmoz approved these changes
@Sammers21 thanks, merging it

2020-08-26 09:44 UTC, olegmoz commented
@Sammers21 cannot merge PR with @g4s8 requesting changes, can't dismiss his review

2020-08-26 09:45 UTC, Sammers21 commented
@olegmoz, try now

2020-08-26 09:54 UTC, olegmoz commented
> @olegmoz, try now

@Sammers21 nothing has changed. Guess I do not have enough permissions to dismiss a review in this repository

2020-09-02 06:36 UTC, merged

2020-09-02 06:57 UTC, 0crat commented
Job audit: performer @vatavuk[/z](https://www.0crat.com/u/vatavuk)[/z](https://www.0crat.com/u/vatavuk) didn't make CR comments

<!-- https://www.0crat.com/footprint/CT2E6TK9B/2df5bdd1-e6e4-4c75-9393-d1ad767c3826, version: 0.54.5, hash: ${buildNumber} -->

2020-09-02 07:00 UTC, 0crat commented
The project doesn't have enough funds, can't make a payment

<!-- https://www.0crat.com/footprint/CT2E6TK9B/99aee4ab-c1ca-4e95-b4c6-a0ddbbda1e7f, version: 0.54.5, hash: ${buildNumber} -->

2020-09-02 07:00 UTC, 0crat commented
Code review was too long (57 days), architects (@g4s8, @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

<!-- https://www.0crat.com/footprint/CT2E6TK9B/12332ab5-91f2-413f-bff8-fc44313f8a94, version: 0.54.5, hash: ${buildNumber} -->