#57 - Add IT with authentication
artipie/helm-adapter pull request #80
Opened 2020-12-01 12:14 UTC by genryxy

Closes #57 
Add IT with authentication

2020-12-01 13:48 UTC, olegmoz requested changes
@genryxy thanks, please see the comments

2020-12-01 13:48 UTC, olegmoz commented on src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
> +     * The helm.
@genryxy I think this field deserves better description

2020-12-01 13:48 UTC, olegmoz commented on src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
> +                        && ("download".equals(perm) || "upload".equals(perm)),
@genryxy I think `Permissions.Single` and `Permissions.Joined` from latest HTTP module could be used here

2020-12-01 13:48 UTC, olegmoz commented on src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
> +    private int helmRepoAdd(final boolean anonymous, final String chartrepo) throws Exception {
@genryxy returned code is always checked against `0`, so I'd suggest to move the comparison inside the method and return `boolean` value indicating if the run was successful or not.

2020-12-01 14:47 UTC, genryxy commented on src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
> +                        && ("download".equals(perm) || "upload".equals(perm)),
@olegmoz do I understand correct that this class could be used here? https://github.com/artipie/http/blob/40e9eadcced3a273b9283af2805d61ef30c559c7/src/main/java/com/artipie/http/auth/JoinedPermissions.java
It has since `0.18` tag and does not have a constructor to pass user and his permissions.

2020-12-01 16:34 UTC, olegmoz commented on src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
> +                        && ("download".equals(perm) || "upload".equals(perm)),
@genryxy it accepts other `Permissions`, so the code could be rewritten as `JoinedPermissions(Permissions.Single(identity.name(), "download"), Permissions.Single(identity.name(), "upload"))`

2020-12-01 19:17 UTC, genryxy commented
@olegmoz thanks, corrected

2020-12-02 13:03 UTC, olegmoz approved these changes
@genryxy thanks, merging

2020-12-02 13:03 UTC, merged