#90 - Obtains `index.yaml` by directory
artipie/helm-adapter pull request #91
Opened 2021-01-19 07:39 UTC by genryxy

Part of #90 
Implemented obtaining `index.yaml` file by directory. In next PR I'll add some negative test cases.

2021-01-19 09:56 UTC, olenagerasimova requested changes
@genryxy thanks, please, check my comment

2021-01-19 09:56 UTC, olenagerasimova commented on src/main/java/com/artipie/helm/metadata/IndexByDirectory.java
> +                .toArray(CompletableFuture[]::new)
@genryxy hm, I'm not sure operations `join` and `completedFuture` are required here, seems like we can collect futures `toArray` right after `thenAcceptBoth`. Moreover, calling blocking `join` here is not a good idea

2021-01-19 19:15 UTC, genryxy commented
@olenagerasimova thanks, sometimes there were problems with concurrency (approximately 10 out of 100 attempts failed) therefore I added `join`. I wrongly assumed that there would be a non-blocking call of `join` as it is nested. Now it was corrected and all test's runs out of 1000 were successful.

2021-01-20 07:33 UTC, olenagerasimova approved these changes
@genryxy thanks, looks good to me

2021-01-20 07:41 UTC, merged

2021-01-20 08:07 UTC, 0crat commented
Job `gh:artipie/helm-adapter#91` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/2390589c-98c4-4d03-9e7b-b33907cf87ec, version: 0.55, hash: ${buildNumber} -->