#96 - Add prefix during download, not use prefix when pushing
artipie/helm-adapter pull request #98
Opened 2021-02-05 15:50 UTC by genryxy

Part of #96 
Stopped using prefix in `PushChartSlice` because now urls are got by dynamically combining. For this purpose, `DownloadIndexSlice` was introduced.

2021-02-11 09:10 UTC, g4s8 requested changes
@genryxy please check my comment

2021-02-11 09:10 UTC, g4s8 commented on src/main/java/com/artipie/helm/http/DownloadIndexSlice.java
> +                                .map(uri -> String.format("%s/%s", this.base, uri))
@genryxy I'd use some `URI` specific classes such as `URI` or `URIBbuilder` for creating and validating `URI` entries

2021-02-11 10:05 UTC, genryxy commented
@g4s8 thanks, corrected

2021-02-12 08:02 UTC, g4s8 approved these changes
@genryxy thanks

2021-02-12 08:02 UTC, merged

2021-02-12 08:20 UTC, 0crat commented
Job audit: `ARC` didn't merge or close PR, performer @g4s8[/z](https://www.0crat.com/u/g4s8)[/z](https://www.0crat.com/u/g4s8) didn't make CR comments

<!-- https://www.0crat.com/footprint/CT2E6TK9B/d4a64f10-80fb-4f02-81ba-70b7b4d8b2e7, version: 0.55, hash: ${buildNumber} -->